### ISSUE TITLE
讨论：保存渲染后DOM（详见内页）

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/web-app-laravel#12]
目前的Diagram渲染是通过DSL->AST->DOM实现的。这个过程还要下载所有依赖的JavaScript和CSS。整个过程要花费1秒钟以上。如果网速不理想还会花更多时间。
这里我们想讨论一下是否应该保存渲染后的DOM+CSS。好处是体积小，不需要运行JavaScript。缺点是将不能支持复杂交互——比如未来隐藏某个Participant。

折中的办法是：先使用缓存的DOM，然后替换成重新渲染的DOM。

**Comment by R0uter** [comment]
Closing this issue since the card moved to done.
