### ISSUE TITLE
在win10环境下执行 npm run build-sequence-core 有报错的情况

### ISSUE THREAD

**Issue by danshuitaihejie** [ZenUml/web-app-laravel#21]
![image](https://user-images.githubusercontent.com/48118719/162641821-f0c570b5-ae16-47ae-90ed-fad3cb78867d.png)

**Comment by R0uter** [comment]
这是个兼容性问题，我来修吧

**Comment by R0uter** [comment]
这个问题是由于Windows 默认没有 cp 命令导致的，可以考虑安装个兼容包……😅 不过我已经改了，复制相关的操作改用js实现，这下应该就不会报错了。
